2018-03-13 10:31:39.437 [error] <0.161.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.166.0> exit with reason normal in context child_terminated
2018-03-13 10:32:39.643 [error] <0.226.0> gen_server <0.226.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:32:39.643 [error] <0.226.0> CRASH REPORT Process <0.226.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:32:39.659 [error] <0.220.0> gen_server <0.220.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:32:39.659 [error] <0.220.0> CRASH REPORT Process <0.220.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:32:39.659 [error] <0.219.0> Supervisor {<0.219.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.5780>, <0.220.0>, <0.224.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49460 -> 127.0.0.1:5672">>) at <0.226.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:32:39.659 [error] <0.219.0> Supervisor {<0.219.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.5780>, <0.220.0>, <0.224.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49460 -> 127.0.0.1:5672">>) at <0.226.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:32:39.659 [error] <0.218.0> Supervisor {<0.218.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.219.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.220.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:32:39.659 [error] <0.218.0> Supervisor {<0.218.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.219.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.220.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:33:39.644 [error] <0.260.0> gen_server <0.260.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:33:39.644 [error] <0.260.0> CRASH REPORT Process <0.260.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:33:39.645 [error] <0.256.0> gen_server <0.256.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:33:39.645 [error] <0.256.0> CRASH REPORT Process <0.256.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:33:39.645 [error] <0.255.0> Supervisor {<0.255.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6118>, <0.256.0>, <0.258.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49464 -> 127.0.0.1:5672">>) at <0.260.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:33:39.645 [error] <0.255.0> Supervisor {<0.255.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6118>, <0.256.0>, <0.258.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49464 -> 127.0.0.1:5672">>) at <0.260.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:33:39.645 [error] <0.254.0> Supervisor {<0.254.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.255.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.256.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:33:39.646 [error] <0.254.0> Supervisor {<0.254.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.255.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.256.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:34:35.239 [error] <0.161.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.166.0> exit with reason normal in context child_terminated
2018-03-13 10:37:54.806 [error] <0.161.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.166.0> exit with reason normal in context child_terminated
2018-03-13 10:40:55.084 [error] <0.226.0> gen_server <0.226.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:40:55.084 [error] <0.226.0> CRASH REPORT Process <0.226.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:40:55.120 [error] <0.220.0> gen_server <0.220.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:40:55.120 [error] <0.220.0> CRASH REPORT Process <0.220.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:40:55.120 [error] <0.219.0> Supervisor {<0.219.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.5759>, <0.220.0>, <0.224.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49511 -> 127.0.0.1:5672">>) at <0.226.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:40:55.120 [error] <0.219.0> Supervisor {<0.219.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.5759>, <0.220.0>, <0.224.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49511 -> 127.0.0.1:5672">>) at <0.226.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:40:55.120 [error] <0.218.0> Supervisor {<0.218.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.219.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.220.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:40:55.121 [error] <0.218.0> Supervisor {<0.218.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.219.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.220.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:41:55.091 [error] <0.249.0> gen_server <0.249.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:41:55.091 [error] <0.249.0> CRASH REPORT Process <0.249.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:41:55.092 [error] <0.245.0> gen_server <0.245.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:41:55.093 [error] <0.245.0> CRASH REPORT Process <0.245.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:41:55.094 [error] <0.244.0> Supervisor {<0.244.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6455>, <0.245.0>, <0.247.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49530 -> 127.0.0.1:5672">>) at <0.249.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:41:55.094 [error] <0.244.0> Supervisor {<0.244.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6455>, <0.245.0>, <0.247.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49530 -> 127.0.0.1:5672">>) at <0.249.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:41:55.094 [error] <0.243.0> Supervisor {<0.243.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.244.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.245.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:41:55.095 [error] <0.243.0> Supervisor {<0.243.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.244.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.245.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:42:55.106 [error] <0.267.0> gen_server <0.267.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:42:55.106 [error] <0.267.0> CRASH REPORT Process <0.267.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:42:55.107 [error] <0.263.0> gen_server <0.263.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:42:55.108 [error] <0.263.0> CRASH REPORT Process <0.263.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:42:55.108 [error] <0.262.0> Supervisor {<0.262.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6540>, <0.263.0>, <0.265.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49565 -> 127.0.0.1:5672">>) at <0.267.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:42:55.108 [error] <0.262.0> Supervisor {<0.262.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6540>, <0.263.0>, <0.265.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49565 -> 127.0.0.1:5672">>) at <0.267.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:42:55.108 [error] <0.261.0> Supervisor {<0.261.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.262.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.263.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:42:55.108 [error] <0.261.0> Supervisor {<0.261.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.262.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.263.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:43:55.125 [error] <0.284.0> gen_server <0.284.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:43:55.126 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:43:55.126 [error] <0.280.0> gen_server <0.280.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:43:55.127 [error] <0.280.0> CRASH REPORT Process <0.280.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:43:55.127 [error] <0.278.0> Supervisor {<0.278.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.279.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.280.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:43:55.127 [error] <0.278.0> Supervisor {<0.278.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.279.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.280.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:43:55.128 [error] <0.279.0> Supervisor {<0.279.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6541>, <0.280.0>, <0.282.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49569 -> 127.0.0.1:5672">>) at <0.284.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:43:55.128 [error] <0.279.0> Supervisor {<0.279.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6541>, <0.280.0>, <0.282.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49569 -> 127.0.0.1:5672">>) at <0.284.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:44:55.141 [error] <0.302.0> gen_server <0.302.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:44:55.141 [error] <0.302.0> CRASH REPORT Process <0.302.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:44:55.142 [error] <0.298.0> gen_server <0.298.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:44:55.142 [error] <0.298.0> CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:44:55.143 [error] <0.297.0> Supervisor {<0.297.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6542>, <0.298.0>, <0.300.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49571 -> 127.0.0.1:5672">>) at <0.302.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:44:55.143 [error] <0.297.0> Supervisor {<0.297.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6542>, <0.298.0>, <0.300.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49571 -> 127.0.0.1:5672">>) at <0.302.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:44:55.143 [error] <0.296.0> Supervisor {<0.296.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.297.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.298.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:44:55.144 [error] <0.296.0> Supervisor {<0.296.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.297.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.298.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:46:55.269 [error] <0.319.0> gen_server <0.319.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:46:55.269 [error] <0.319.0> CRASH REPORT Process <0.319.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:46:55.271 [error] <0.315.0> gen_server <0.315.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:46:55.271 [error] <0.315.0> CRASH REPORT Process <0.315.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:46:55.271 [error] <0.313.0> Supervisor {<0.313.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.314.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.315.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:46:55.271 [error] <0.313.0> Supervisor {<0.313.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.314.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.315.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:46:55.271 [error] <0.314.0> Supervisor {<0.314.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6543>, <0.315.0>, <0.317.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49573 -> 127.0.0.1:5672">>) at <0.319.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:46:55.271 [error] <0.314.0> Supervisor {<0.314.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6543>, <0.315.0>, <0.317.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49573 -> 127.0.0.1:5672">>) at <0.319.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:47:55.284 [error] <0.338.0> gen_server <0.338.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:47:55.284 [error] <0.338.0> CRASH REPORT Process <0.338.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:47:55.285 [error] <0.334.0> gen_server <0.334.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:47:55.285 [error] <0.334.0> CRASH REPORT Process <0.334.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:47:55.285 [error] <0.333.0> Supervisor {<0.333.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6544>, <0.334.0>, <0.336.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49578 -> 127.0.0.1:5672">>) at <0.338.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:47:55.286 [error] <0.333.0> Supervisor {<0.333.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6544>, <0.334.0>, <0.336.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49578 -> 127.0.0.1:5672">>) at <0.338.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:47:55.286 [error] <0.332.0> Supervisor {<0.332.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.333.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.334.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:47:55.286 [error] <0.332.0> Supervisor {<0.332.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.333.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.334.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:48:55.299 [error] <0.357.0> gen_server <0.357.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:48:55.299 [error] <0.357.0> CRASH REPORT Process <0.357.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:48:55.300 [error] <0.353.0> gen_server <0.353.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:48:55.301 [error] <0.353.0> CRASH REPORT Process <0.353.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:48:55.301 [error] <0.351.0> Supervisor {<0.351.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.352.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.353.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:48:55.301 [error] <0.351.0> Supervisor {<0.351.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.352.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.353.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:48:55.302 [error] <0.352.0> Supervisor {<0.352.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6545>, <0.353.0>, <0.355.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49599 -> 127.0.0.1:5672">>) at <0.357.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:48:55.302 [error] <0.352.0> Supervisor {<0.352.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6545>, <0.353.0>, <0.355.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49599 -> 127.0.0.1:5672">>) at <0.357.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:52:34.419 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-03-13 10:52:45.866 [error] <0.161.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.166.0> exit with reason normal in context child_terminated
2018-03-13 10:53:45.998 [error] <0.226.0> gen_server <0.226.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:53:45.998 [error] <0.226.0> CRASH REPORT Process <0.226.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:53:46.025 [error] <0.220.0> gen_server <0.220.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:53:46.025 [error] <0.220.0> CRASH REPORT Process <0.220.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:53:46.025 [error] <0.219.0> Supervisor {<0.219.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.5780>, <0.220.0>, <0.224.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49671 -> 127.0.0.1:5672">>) at <0.226.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:53:46.025 [error] <0.219.0> Supervisor {<0.219.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.5780>, <0.220.0>, <0.224.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49671 -> 127.0.0.1:5672">>) at <0.226.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:53:46.026 [error] <0.218.0> Supervisor {<0.218.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.219.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.220.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:53:46.026 [error] <0.218.0> Supervisor {<0.218.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.219.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.220.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:56:16.088 [error] <0.243.0> gen_server <0.243.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:56:16.089 [error] <0.243.0> CRASH REPORT Process <0.243.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:56:16.090 [error] <0.239.0> gen_server <0.239.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:56:16.090 [error] <0.239.0> CRASH REPORT Process <0.239.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:56:16.090 [error] <0.238.0> Supervisor {<0.238.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6313>, <0.239.0>, <0.241.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49673 -> 127.0.0.1:5672">>) at <0.243.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:56:16.090 [error] <0.238.0> Supervisor {<0.238.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6313>, <0.239.0>, <0.241.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49673 -> 127.0.0.1:5672">>) at <0.243.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:56:16.090 [error] <0.237.0> Supervisor {<0.237.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.238.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.239.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:56:16.091 [error] <0.237.0> Supervisor {<0.237.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.238.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.239.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:57:11.308 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.180.0> exit with reason normal in context child_terminated
2018-03-13 10:58:11.438 [error] <0.240.0> gen_server <0.240.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:58:11.438 [error] <0.240.0> CRASH REPORT Process <0.240.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:58:11.492 [error] <0.234.0> gen_server <0.234.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:58:11.492 [error] <0.234.0> CRASH REPORT Process <0.234.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:58:11.492 [error] <0.233.0> Supervisor {<0.233.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6299>, <0.234.0>, <0.238.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49704 -> 127.0.0.1:5672">>) at <0.240.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:58:11.492 [error] <0.233.0> Supervisor {<0.233.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6299>, <0.234.0>, <0.238.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49704 -> 127.0.0.1:5672">>) at <0.240.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:58:11.492 [error] <0.232.0> Supervisor {<0.232.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.233.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.234.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:58:11.492 [error] <0.232.0> Supervisor {<0.232.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.233.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.234.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:59:11.444 [error] <0.255.0> gen_server <0.255.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:59:11.444 [error] <0.255.0> CRASH REPORT Process <0.255.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:59:11.445 [error] <0.251.0> gen_server <0.251.0> terminated with reason: {socket_error,timeout}
2018-03-13 10:59:11.445 [error] <0.251.0> CRASH REPORT Process <0.251.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 10:59:11.445 [error] <0.250.0> Supervisor {<0.250.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6636>, <0.251.0>, <0.253.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49713 -> 127.0.0.1:5672">>) at <0.255.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:59:11.446 [error] <0.250.0> Supervisor {<0.250.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6636>, <0.251.0>, <0.253.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49713 -> 127.0.0.1:5672">>) at <0.255.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 10:59:11.446 [error] <0.249.0> Supervisor {<0.249.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.250.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.251.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 10:59:11.446 [error] <0.249.0> Supervisor {<0.249.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.250.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.251.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 11:00:11.459 [error] <0.270.0> gen_server <0.270.0> terminated with reason: {socket_error,timeout}
2018-03-13 11:00:11.460 [error] <0.266.0> gen_server <0.266.0> terminated with reason: {socket_error,timeout}
2018-03-13 11:00:11.460 [error] <0.270.0> CRASH REPORT Process <0.270.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 11:00:11.461 [error] <0.266.0> CRASH REPORT Process <0.266.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 11:00:11.461 [error] <0.265.0> Supervisor {<0.265.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6700>, <0.266.0>, <0.268.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49725 -> 127.0.0.1:5672">>) at <0.270.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 11:00:11.461 [error] <0.265.0> Supervisor {<0.265.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6700>, <0.266.0>, <0.268.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49725 -> 127.0.0.1:5672">>) at <0.270.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 11:00:11.461 [error] <0.264.0> Supervisor {<0.264.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.265.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.266.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 11:00:11.462 [error] <0.264.0> Supervisor {<0.264.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.265.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.266.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 11:01:11.474 [error] <0.284.0> gen_server <0.284.0> terminated with reason: {socket_error,timeout}
2018-03-13 11:01:11.474 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 11:01:11.475 [error] <0.280.0> gen_server <0.280.0> terminated with reason: {socket_error,timeout}
2018-03-13 11:01:11.475 [error] <0.280.0> CRASH REPORT Process <0.280.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 11:01:11.476 [error] <0.279.0> Supervisor {<0.279.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6701>, <0.280.0>, <0.282.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49770 -> 127.0.0.1:5672">>) at <0.284.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 11:01:11.476 [error] <0.279.0> Supervisor {<0.279.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6701>, <0.280.0>, <0.282.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49770 -> 127.0.0.1:5672">>) at <0.284.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 11:01:11.476 [error] <0.278.0> Supervisor {<0.278.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.279.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.280.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 11:01:11.477 [error] <0.278.0> Supervisor {<0.278.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.279.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.280.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 11:03:41.632 [error] <0.299.0> gen_server <0.299.0> terminated with reason: {socket_error,timeout}
2018-03-13 11:03:41.632 [error] <0.299.0> CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 11:03:41.633 [error] <0.295.0> gen_server <0.295.0> terminated with reason: {socket_error,timeout}
2018-03-13 11:03:41.633 [error] <0.295.0> CRASH REPORT Process <0.295.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 11:03:41.634 [error] <0.293.0> Supervisor {<0.293.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.294.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.295.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 11:03:41.634 [error] <0.293.0> Supervisor {<0.293.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.294.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.295.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 11:03:41.634 [error] <0.294.0> Supervisor {<0.294.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6702>, <0.295.0>, <0.297.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49773 -> 127.0.0.1:5672">>) at <0.299.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 11:03:41.634 [error] <0.294.0> Supervisor {<0.294.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6702>, <0.295.0>, <0.297.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49773 -> 127.0.0.1:5672">>) at <0.299.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 11:04:41.646 [error] <0.315.0> gen_server <0.315.0> terminated with reason: {socket_error,timeout}
2018-03-13 11:04:41.646 [error] <0.315.0> CRASH REPORT Process <0.315.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 11:04:41.647 [error] <0.311.0> gen_server <0.311.0> terminated with reason: {socket_error,timeout}
2018-03-13 11:04:41.647 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 11:04:41.647 [error] <0.310.0> Supervisor {<0.310.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6708>, <0.311.0>, <0.313.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49796 -> 127.0.0.1:5672">>) at <0.315.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 11:04:41.647 [error] <0.310.0> Supervisor {<0.310.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6708>, <0.311.0>, <0.313.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49796 -> 127.0.0.1:5672">>) at <0.315.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 11:04:41.647 [error] <0.309.0> Supervisor {<0.309.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.310.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.311.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 11:04:41.648 [error] <0.309.0> Supervisor {<0.309.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.310.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.311.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 11:05:06.624 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.180.0> exit with reason normal in context child_terminated
2018-03-13 11:06:06.773 [error] <0.240.0> gen_server <0.240.0> terminated with reason: {socket_error,timeout}
2018-03-13 11:06:06.773 [error] <0.240.0> CRASH REPORT Process <0.240.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 11:06:06.802 [error] <0.234.0> gen_server <0.234.0> terminated with reason: {socket_error,timeout}
2018-03-13 11:06:06.802 [error] <0.234.0> CRASH REPORT Process <0.234.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 11:06:06.803 [error] <0.233.0> Supervisor {<0.233.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6301>, <0.234.0>, <0.238.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49806 -> 127.0.0.1:5672">>) at <0.240.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 11:06:06.803 [error] <0.233.0> Supervisor {<0.233.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6301>, <0.234.0>, <0.238.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49806 -> 127.0.0.1:5672">>) at <0.240.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 11:06:06.803 [error] <0.232.0> Supervisor {<0.232.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.233.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.234.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 11:06:06.803 [error] <0.232.0> Supervisor {<0.232.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.233.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.234.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 11:07:06.781 [error] <0.255.0> gen_server <0.255.0> terminated with reason: {socket_error,timeout}
2018-03-13 11:07:06.781 [error] <0.255.0> CRASH REPORT Process <0.255.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 11:07:06.782 [error] <0.251.0> gen_server <0.251.0> terminated with reason: {socket_error,timeout}
2018-03-13 11:07:06.782 [error] <0.251.0> CRASH REPORT Process <0.251.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-13 11:07:06.782 [error] <0.249.0> Supervisor {<0.249.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.250.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.251.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 11:07:06.782 [error] <0.249.0> Supervisor {<0.249.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.250.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.251.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-13 11:07:06.782 [error] <0.250.0> Supervisor {<0.250.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6617>, <0.251.0>, <0.253.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49827 -> 127.0.0.1:5672">>) at <0.255.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-13 11:07:06.783 [error] <0.250.0> Supervisor {<0.250.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6617>, <0.251.0>, <0.253.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49827 -> 127.0.0.1:5672">>) at <0.255.0> exit with reason reached_max_restart_intensity in context shutdown
